// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheCakeFactory.Models;

namespace TheCakeFactory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheCakeFactory.Models.CookingStep", b =>
                {
                    b.Property<int>("CookingStepId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CookingStepNumber");

                    b.Property<string>("Description");

                    b.Property<int>("RecipeId");

                    b.Property<string>("RecipeName");

                    b.HasKey("CookingStepId");

                    b.ToTable("CookingSteps");
                });

            modelBuilder.Entity("TheCakeFactory.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Chef");

                    b.Property<int>("Cook");

                    b.Property<string>("Dificulty");

                    b.Property<string>("Ingredients");

                    b.Property<string>("Name");

                    b.Property<int>("Preparation");

                    b.Property<string>("Review");

                    b.Property<int>("Stars");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
